### ISSUE TITLE
Bug: 이미지 하루 지나면 삭제 되는 문제

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#216]
## 어떤 버그인가요?

유저, 일기 이미지를 올리고 하루가 지나면 삭제

## 어떤 상황에서 발생한 버그인가요?

유저 이미지 업데이트 혹은 일기 이미지 업로드 이후 하루가 지나면 이미지가 삭제되어 있음

## 예상 결과

기간이 얼마나 지나도 삭제되지 않아야 함

**Comment by HyunJinNo** [comment]
하루 지나도 일기 이미지가 삭제되지 않음을 확인했습니다.
