### ISSUE TITLE
Feature: information page nation 필터링

### ISSUE THREAD

**Issue by hyeonjaez** [TripInfoWeb/solitour-backend#37]
## 어떤 기능인가요?

information 메인 페이지 페이지네이션 및 필터링 및 정렬
회원인지 판별은 어떻게 하냐?
- Cookie에서 access_token 또는 refresh_token을 찾아서 판별 후 userId 가져오기

## Todo

- [x] default 는 카테고리 id와 최신순으로
- [x] 좋아요 순
- [x] 조회 순
- [x] 지역 카테고리 별

**Comment by HyunJinNo** [comment]
https://www.notion.so/9-2-77e196a8a1e24c4897a1684081a3f9e3

노션에 해당 내용 정리해봤습니다.

**Comment by Astin01** [comment]
로그인이 되었다면 access token 이 쿠키에 들어가 있으므로 @AuthenticationPrincipal Long userid 를 쓰시면 백엔드에서 userId를 활용하실 수 있습니다
